version: '3.3'

services:
  registry:
    container_name: registry
    restart: always
    image: registry
    ports:
      - 5000:5000
    volumes:
      - ./config/config.yml:/etc/docker/registry/config.yml:ro
      - ./data:/mnt/registry:rw
